### ISSUE TITLE
Incorrect payout

### ISSUE THREAD

**Issue by MiningCryptoLive** [e4p1k0/etchash-solo-pool#2]
I set this pool up a few months ago. Everything works except the payout. Something in the code is incorrect, if more than one miner is on the pool they still get a share of the block. So it's not paying Solo correctly. It pays the miner the full block but any other miners also get a percentage.

**Comment by btclinux** [comment]
I just look in my db, all miners have zero balances except those who find uncles because payout threshold is 3 ETC
